steps:
- id: 'validator binary'
  name: 'gcr.io/cloud-builders/docker:18.09.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
   
       chmod 755 terraform-validator-linux-amd64; ./terraform-validator-linux-amd64 validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library/ --project=$PROJECT_ID >> /workspace/result.txt  
      else
        echo "******************************* SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
      
- id: "Read Values"
  name: gcr.io/cloud-builders/git
  entrypoint: 'sh'
  args:
    - -c
    - |
      # Read from "/workspace"
      echo "Found violations we saved " $(cat /workspace/result.txt) 
