steps:
- id: 'validator binary'
  name: 'gcr.io/cloud-builders/docker:18.09.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
   
       chmod 755 terraform-validator-linux-amd64;
       ./terraform-validator-linux-amd64 validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library/ --project=$PROJECT_ID >> /workspace/result.txt 
       cat /workspace/result.txt
      else
        echo " Relevant resources didn't exist......"
      fi
      
- id: Save validator result to GCS 
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r','/workspace/result.txt','gs://tfcode_vali/$BUILD_ID/result.txt']


- id: 'Apply on GCP'
  name: 'gcr.io/cloud-builders/docker:18.09.6'
  #name: 'centos:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      #if [ -e "/workspace/result.txt" ]; then
          fcount=0;
          fcount=`grep "Constraint" /workspace/result.txt | awk '{print $1}'|sort| uniq -c|awk '{print $1}'`;
            echo "$fcount";
         if [ $fcount != 0 ];then
             echo "Don't execute [terraform apply] resources";
          else 
              echo "apply on resources";
       fi
      #else
        #echo "Result file didn't generate/exist";
    #fi
