steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://terraform-validator/releases/2019-11-07/terraform-validator-linux-amd64', '.']
  
- id: 'tf validator'
  name: 'masterjey/tf-validator'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
         cd consolidated/;ls -ltr
         pwd
         sleep 20
         cd consolidated/policy-library/;ls -ltr
         pwd
         export _POLICY_PATH=/workspace/consolidated/policy-library
      docker run -d -i -t masterjey/tf-validator validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=${_POLICY_PATH}
      else
        echo "***************************** SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
