steps:  
- id: 'tf validator'
  name: 'masterjey/tf-validator'
  #entrypoint: 'sh'
  args: ['masterjey/tf-validator','validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library']
