steps:
- id: 'tf validator'
  name: 'alpine'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "cloudresources/" ]; then
        pwd
       
        cd cloudresources/;ls -ltr
        bash terraform-validator-linux-amd64 validate cloudresources/tfplan900.tfplan.json --policy-path=/policy-library
      else
        echo "***************************** SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
