steps:
- id: 'tf validator'
  name: 'masterjey/tf-validator'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "cloudresources/" ]; then
       cd tfvalidation-pipeline; ls -ltr; 
        docker run -d -i -t masterjey/tf-validator validate cloudresources/tfplan900.tfplan.json --policy-path=/policy-library
      else
        echo "***************************** SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
