steps:

- id: 'tf init'
  name: 'hashicorp/terraform:0.12.8'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
        cd consolidated/cloudresources
        terraform init
      else
        echo " Relevant resources didn't exist......"
          #terraform init || exit 1
      fi 

- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.8'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "consolidated/" ]; then
        cd consolidated/cloudresources
        terraform plan -out=tfplanoutput.tfplan && terraform show -json tfplanoutput.tfplan > /workspace/tfplanoutputv12.tfplan.json
        ls -ltr
        #terraform plan -out=planop.tfplan
        #terraform show -json planop.tfplan > planop.tfplan.json
      else
        echo "Terraform plan error......"
          #terraform plan || exit 1   
      fi 

- id: Save terraform plan json output to GCS 
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r','/workspace/tfplanoutputv12.tfplan.json','gs://tfcode_vali/$BUILD_ID/tfplanoutputv12.tfplan.json']

- id: 'validate tfplan output'
  name: 'hashicorp/terraform:0.12.8' #'gcr.io/cloud-builders/docker:18.09.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
   
       chmod 755 terraform-validator-linux-amd64;
       ./terraform-validator-linux-amd64 validate consolidated/cloudresources/testplanoutput.tfplan.json --policy-path=consolidated/policy-library/ --project=$PROJECT_ID >> /workspace/result.txt 
        status="$?";
        echo "Status code:$status" >> /workspace/result.txt
        cat /workspace/result.txt
        
            if [ $status != 0 ];then
              echo "Security Violation Found...Don't execute code for cloud resources";
             else 
                echo "No security Violation found...Apply on resources";
                #terraform apply -auto-approve
            fi
      else
        echo " Relevant resources didn't exist......"
      fi

     
- id: Save validator results to GCS 
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r','/workspace/result.txt','gs://tfcode_vali/$BUILD_ID/result.txt']

