steps:

- id: 'tf init'
  name: 'hashicorp/terraform:0.12.8'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
        cd consolidated/cloudresources
        terraform init
      else
        echo " Relevant resources didn't exist......"
          #terraform init || exit 1
      fi 

- id: Pull a key from GCS 
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r','gs://secretstore-test/key.json','/workspace/key.json']
  
- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.8'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "consolidated/" ]; then
        cd consolidated/cloudresources
        pwd
        terraform plan -out=tfplanoutput.tfplan && terraform show -json tfplanoutput.tfplan >> /workspace/consolidated/cloudresources/tfplanoutputv12.tfplan.json
        ls -ltr
      else
        echo "Terraform plan error......"
          #terraform plan || exit 1   
      fi 

- id: Save terraform plan json output to GCS 
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r','/workspace/consolidated/cloudresources/tfplanoutputv12.tfplan.json','gs://tfcode_vali/$BUILD_ID/tfplanoutputv12.tfplan.json']

- id: 'validate tfplan output'
  name: 'hashicorp/terraform:0.12.8' #'gcr.io/cloud-builders/docker:18.09.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
   
       chmod 755 terraform-validator-linux-amd64;
       ./terraform-validator-linux-amd64 validate consolidated/cloudresources/tfplanoutputv12.tfplan.json --policy-path=consolidated/policy-library/ --project=$PROJECT_ID >> /workspace/violation-results.txt 
        status="$?";
        echo "Status code:$status" >> /workspace/violation-results.txt
        cat /workspace/violation-results.txt
        
            if [ $status != 2 ];then
              echo "Security Violation Found...Don't execute code for cloud resources";
             else 
                echo "No security Violation found...Applying on resources";
                #terraform apply "tfplanoutput.tfplan"
            fi
      else
        echo " Relevant resources didn't exist......"
      fi

     
- id: Save validator results to GCS 
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r','/workspace/violation-results.txt','gs://tfcode_vali/$BUILD_ID/violation-results.txt']
