steps:
- id: 'tf validator'
  name: 'masterjey/tf-validator'

- name: 'gcr.io/cloud-builders/docker'
  args: ["run", "-t", "masterjey/tf-validator validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library"]
