steps:  
- id: 'tf validator'
  name: 'masterjey/tf-validator'

  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
      validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library --project=$PROJECT_ID
        else
        echo "***************************** SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
