steps:  
- id: 'tf validator'
  name: 'masterjey/tf-validator'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
      validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library
      else
        echo "***************************** SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
