steps:
#- id: 'validator binary'
  #name: 'gcr.io/cloud-builders/gsutil'
  #args: ['cp', 'gs://terraform-validator/releases/2019-11-07/terraform-validator-linux-amd64', '.']

- name: 'ubuntu:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
      sudo cp /etc/ssl/certs/ca-certificates.crt  /usr/local/share/ca-certificates/ca-certificates.crt
      sudo update-ca-certificates
        
       chmod 755 terraform-validator-linux-amd64; ./terraform-validator-linux-amd64 validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library/ --ancestry organization/913144897837/projects/p-02-08-19-gcp-lab-admin4  
      else
        echo "******************************* SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi

  
  #args: ['./terraform-validator-linux-amd64 validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library']
