steps:
- id: 'tf validator'
  name: 'thazelart/terraform-validator'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "cloudresources/" ]; then
        cd tfvalidation-pipeline;ls -ltr
        chmod 755 tfvalidation-pipeline/terraform-validator-linux-amd64;
        tfvalidation-pipeline/terraform-validator-linux-amd64 validate cloudresources/tfplan900.tfplan.json --policy-path=/policy-library
      else
        echo "***************************** SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
