steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://terraform-validator/releases/2019-11-07/terraform-validator-linux-amd64', '.']
  
- id: 'tf validator'
  name: 'masterjey/tf-validator'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "cloudresources/" && policy-library/ ]; then
         cd cloudresources/;ls -ltr
         cd policy-library/; ls -ltr
         export POLICY_PATH=/policy-library
      docker run -d -i -t masterjey/tf-validator validate cloudresources/tfplan900.tfplan.json --policy-path=/policy-library
      else
        echo "***************************** SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
