steps:
- id: 'tf validator'
  name: 'thazelart/terraform-validator'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "cloudresources/" ]; then
        cd cloudresources/;ls -ltr
        terraform-validator validate cloudresources/tfplan900.tfplan.json --policy-path=/policy-library
      else
        echo "***************************** SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
