steps:
- id: 'validator binary'
  name: 'gcr.io/cloud-builders/docker:18.09.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "consolidated/" ]; then
   
       chmod 755 terraform-validator-linux-amd64; ./terraform-validator-linux-amd64 validate consolidated/cloudresources/tfplan900.tfplan.json --policy-path=consolidated/policy-library/ --ancestry organization/913144897837/projects/p-02-08-19-gcp-lab-admin4  
      else
        echo "******************************* SKIPPING *******************************"
        echo " Error in excecution......"
        echo "*******************************************************************************"
      fi
