steps:  
- id: 'tf validator'
  name: 'masterjey/tf-validator'
  args: 
  - 'validate'
  - 'consolidated/cloudresources/tfplan900.tfplan.json'
  - '--policy-path=consolidated/policy-library'
  - '--project=p-02-08-19-gcp-lab-admin4'
